import type { Group } from "~/routes/admin/groups-management";

export const mockGroups: Group[] = [
  {
    id: 1,
    groupName: "Engineering",
    managers: ["Utkarsh", "Mishra"],
    members: [
      "Utkarsh",
      "Mishra",
      "Manish",
      "Pizza",
      "Jane Doe",
      "Alex Carter",
      "Manish",
      "Pizza",
      "Jane Doe",
      "Alex Carter",
      "Sarah Smith",
      "Sarah Smith",
    ],
    status: "Active",
  },
  {
    id: 2,
    groupName: "Marketing",
    managers: ["Jane Doe"],
    members: [
      "Jane Doe",
      "Tom Green",
      "Emily White",
      "Robert King",
      "Olivia Lewis",
    ],
    status: "Active",
  },
  {
    id: 3,
    groupName: "No-Code",
    managers: ["Manish"],
    members: ["Manish", "Liam Walker", "Sophia Hall", "Daniel Reed"],
    status: "Inactive",
  },
  {
    id: 4,
    groupName: "Leadership",
    managers: ["Utkarsh", "Mishra"],
    members: [
      "Utkarsh",
      "Mishra",
      "Jane Doe",
      "Michael Johnson",
      "Laura Thompson",
    ],
    status: "Active",
  },
  {
    id: 5,
    groupName: "HR & Operations",
    managers: ["Sarah Smith"],
    members: [
      "Sarah Smith",
      "Kevin Brown",
      "Hannah Davis",
      "Emma Wilson",
      "Chris Martin",
    ],
    status: "Inactive",
  },
];
